### ISSUE TITLE
Data form in Pipeliner

### ISSUE THREAD

**Issue by hyperswitcher** [neuro-ml/reskit#11]
Now Pipeliners cannot handle usual transformers from sklearn without additional function creation and putting it to DataTransformer. I think it's better to keep usual (X, y) form in all functions and classes. And if you have more than two arrays to use, we can store it in X.

**Comment by lodurality** [comment]
Good thinking.

I think we should two types of transformers: one in usual (X,y) format and other in our dictionary format (because it is useful for a lot of tasks).

**Comment by hyperswitcher** [comment]
Rewrote reskit transformers and whole reskit interface to (X, y) form of input. Any our custom transformer, of course, can use X as a dictionary, so we got what we wanted.
